version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run migrate:latest && npm start"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXTAUTH_URL: http://localhost:3000
    volumes:
      - ./front-end:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

volumes:
  db_data:
