version: "4"
services:
  # Create database container
  db:
    container_name: database-docker
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"

  backend:
    # Create backend container  
    container_name: backend-docker
    build: ./back-end
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:root@db/postgres
      - API_URL=http://host.docker.internal:8000
    volumes:
      - ./back-end/src/data/data-docker:/var/lib/postgresql/data
    restart: always
    ports:
      - "8000:8000"

  # Create frontend container
  frontend:
    container_name: frontend-docker
    build: ./front-end
    depends_on:
      - backend
    links:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8000
    volumes:
      - ./front-end:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
      - /usr/src/app/frontend/.next
    restart: always
    ports:
      - 3000:3000 