version: '4'
services:
  # Create database container
  db:
    container_name: database-docker
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always

  backend:
    # Create backend container  
    container_name: backend-docker
    build: ./back-end
    environment:
      DATABASE_URL: postgres://postgres:root@db/postgres
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/src/data/data-docker:/var/lib/postgresql/data
    restart: always

  # Create frontend container
  frontend:
    container_name: frontend-docker
    build: ./front-end
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3000:3000 
    restart: always