import "../styles/globals.css"
import type { AppProps } from "next/app";
import Head from "next/head";

import { AuthProvider } from "../src/contexts/AuthContext";

// import { GlobalStyles } from "../styles/GlobalStyles";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
          <title>Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
       <AuthProvider>
          <Component {...pageProps} />
       </AuthProvider>
    </>
  );
};
